Traceback (most recent call last):
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/akirakawai/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# https://ahlive.readthedocs.io/en/latest/introductions/overview.html

import ahlive as ah
df = ah.open_dataset(label='annual_co2')
ah_df = ah.DataFrame(df, xs='year', ys='co2_ppm')
ah_df.render()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-1310f73dd601>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# https://ahlive.readthedocs.io/en/latest/introductions/overview.html[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0;32mimport[0m [0mahlive[0m [0;32mas[0m [0mah[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0mdf[0m [0;34m=[0m [0mah[0m[0;34m.[0m[0mopen_dataset[0m[0;34m([0m[0mlabel[0m[0;34m=[0m[0;34m'annual_co2'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mah_df[0m [0;34m=[0m [0mah[0m[0;34m.[0m[0mDataFrame[0m[0;34m([0m[0mdf[0m[0;34m,[0m [0mxs[0m[0;34m=[0m[0;34m'year'[0m[0;34m,[0m [0mys[0m[0;34m=[0m[0;34m'co2_ppm'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'ahlive'
ModuleNotFoundError: No module named 'ahlive'

