Traceback (most recent call last):
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/akirakawai/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for i in range(sample.shape[0]):
    plt.plot(x, mean, 'ro', markersize=4)
    plt.errorbar(x, mean, yerr=error[i], ecolor='gray', linestyle='')

plt.ylim([0, 12])
plt.legend(['mean'])
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-5-cca3bb26beab>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mfor[0m [0mi[0m [0;32min[0m [0mrange[0m[0;34m([0m[0msample[0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m     [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mx[0m[0;34m,[0m [0mmean[0m[0;34m,[0m [0;34m'ro'[0m[0;34m,[0m [0mmarkersize[0m[0;34m=[0m[0;36m4[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m     [0mplt[0m[0;34m.[0m[0merrorbar[0m[0;34m([0m[0mx[0m[0;34m,[0m [0mmean[0m[0;34m,[0m [0myerr[0m[0;34m=[0m[0merror[0m[0;34m[[0m[0mi[0m[0;34m][0m[0;34m,[0m [0mecolor[0m[0;34m=[0m[0;34m'gray'[0m[0;34m,[0m [0mlinestyle[0m[0;34m=[0m[0;34m''[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0mplt[0m[0;34m.[0m[0mylim[0m[0;34m([0m[0;34m[[0m[0;36m0[0m[0;34m,[0m [0;36m12[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'x' is not defined
NameError: name 'x' is not defined

