Traceback (most recent call last):
  File "/Users/akirakawai/Library/Python/3.8/lib/python/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Library/Python/3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Python/3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Library/Python/3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Library/Python/3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Library/Python/3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Library/Python/3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# https://qiita.com/osanshouo/items/3c66781f41884694838b
import matplotlib.pyplot as plt
from matplotlib import animation, rc
from IPython.display import HTML

import numpy as np
%matplotlib inline

fig = plt.figure()
ax = fig.add_subplot(111, aspect=1)

theta = np.linspace(0, 2*np.pi, 128)

def update(f):
    ax.cla() # ax ã‚’ã‚¯ãƒªã‚¢
    ax.grid()
    ax.plot(np.cos(theta), np.sin(theta), c="gray")
    ax.plot(np.cos(f), np.sin(f), "o", c="red")

anim = FuncAnimation(fig, update, frames=np.pi*np.arange(0,2,0.25), interval=200)

# anim.save("c03.gif", writer="imagemagick")
# plt.close()
HTML(anim.to_html5_video())


------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-bbc563127d94>[0m in [0;36m<module>[0;34m[0m
[1;32m     18[0m     [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mnp[0m[0;34m.[0m[0mcos[0m[0;34m([0m[0mf[0m[0;34m)[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0msin[0m[0;34m([0m[0mf[0m[0;34m)[0m[0;34m,[0m [0;34m"o"[0m[0;34m,[0m [0mc[0m[0;34m=[0m[0;34m"red"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     19[0m [0;34m[0m[0m
[0;32m---> 20[0;31m [0manim[0m [0;34m=[0m [0mFuncAnimation[0m[0;34m([0m[0mfig[0m[0;34m,[0m [0mupdate[0m[0;34m,[0m [0mframes[0m[0;34m=[0m[0mnp[0m[0;34m.[0m[0mpi[0m[0;34m*[0m[0mnp[0m[0;34m.[0m[0marange[0m[0;34m([0m[0;36m0[0m[0;34m,[0m[0;36m2[0m[0;34m,[0m[0;36m0.25[0m[0;34m)[0m[0;34m,[0m [0minterval[0m[0;34m=[0m[0;36m200[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     21[0m [0;34m[0m[0m
[1;32m     22[0m [0;31m# anim.save("c03.gif", writer="imagemagick")[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'FuncAnimation' is not defined
NameError: name 'FuncAnimation' is not defined

