Traceback (most recent call last):
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/akirakawai/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/akirakawai/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# „Åæ„Åö„ÅØÁîªÂÉè„ÇíË™≠„ÅøËæº„ÇÄ
img = cv2.imread('src/lena.png')
img.dtype, img.shape
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-2-1cde11488c31>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# „Åæ„Åö„ÅØÁîªÂÉè„ÇíË™≠„ÅøËæº„ÇÄ[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mimg[0m [0;34m=[0m [0mcv2[0m[0;34m.[0m[0mimread[0m[0;34m([0m[0;34m'src/lena.png'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mimg[0m[0;34m.[0m[0mdtype[0m[0;34m,[0m [0mimg[0m[0;34m.[0m[0mshape[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mAttributeError[0m: 'NoneType' object has no attribute 'dtype'
AttributeError: 'NoneType' object has no attribute 'dtype'

